### ISSUE TITLE
Failed to open process

### ISSUE THREAD

**Issue by SatrioKamaludin** [mmozeiko/aes-finder#7] opened 2018-03-24 13:58 UTC
I've managed to compile the program using VS 2013. But it failed to search AES keys for some reason.
![failed](https://user-images.githubusercontent.com/8587427/37864790-dac203b4-2fa5-11e8-8a21-2d7f4232b6b3.PNG)
I'm currently using windows 10.

**Comment by mmozeiko** [comment] 2018-03-25 04:05
Does your user have administrator rights?

Can you try opening cmd.exe as administrator (Start -> type cmd.exe, right click on it and select "Run as administrator") and then run the executable? Is it working then?

If that does not help, then set breakpoint after call to `OpenProcess` and check last error code (`GetLastError()` function). That should help to understand why opening process fails.

**Comment by Blenux** [comment] 2018-04-15 09:19
I think the issue is trying to get AES key but with anti-decryption feature, like works for some programs I have tried, but main one is Fortnite comes up with failed to open process also...

**Comment by mmozeiko** [comment] 2018-04-15 10:29
What is "anti-decryption feature" ?

I just tried running it on Fortnite process, it works fine for me - OpenProcess succeeds. (64-bit Windows 10). But there is a different issue, that it cannot read its memory at all... ReadProcessMemory returns ERROR_ACCESS_DENIED, but that is very different error from screenshot above where OpenProcess fails. 

Probably anti-cheat is doing some tricky stuff. Maybe injecting dll into target process that will read its own memory and send to you would work... Don't know. Anyway this is out of scope of this utility. If you can get memory dump of process, you can easily run it offline on dump.

**Comment by Blenux** [comment] 2018-04-15 13:08
Yeah sorry bad wording on my part, but yeah for me it just comes up has failed to load process, running CMD has Admin etc, then aes-finder.exe -FortniteClient-Win64-Shipping.exe or it's PID number comes back with 

Searching PID XXXXX .....
Failed to open Process
Done!

(XXXX is for the random number that comes up)

Worked fine on the EAC one, but key isn't the right one for Fortnite itself.....

oh ok was hoping to get the AES key, need it to export the latest models with uModel but no one is sharing the AES key no more.......

**Comment by mmozeiko** [comment] 2018-04-15 20:47
If you use `-` before argument then program will think you want to use PID number. Basically it accepts two type of arguments:

    aes-finder.exe -12345

where 12345 is pid number (integer) or

    aes-finder.exe program.exe

In this case it will find all PIDs for running program.exe process(es) automatically.
Check the readme for more examples.

If you use `-program.exe` that's wrong, it will try to reinterpret "program.exe" as integer and will fail terribly thus producing "random" number as PID.

**Comment by Blenux** [comment] 2018-04-16 01:18
Yeah bad typing there again damn it lol, I use - only for PID and without - on the fortnite exe, but still fails to open, the game uses EasyAntiCheat, if you uninstall that the game won't launch, but am able to get AES key for the EAC exe (Not the shipping exe because it closes soon has it detects no EasyAntiCheat), sadly that's not the right key to open the PAK files with uModel.

![fort](https://user-images.githubusercontent.com/25260650/38785878-69832da8-4167-11e8-9e6b-2cd56625f084.PNG)
.

**Comment by mmozeiko** [comment] 2018-04-16 02:06
That's the same process I've tried:

![image](https://user-images.githubusercontent.com/1665010/38786955-0a645e64-40e0-11e8-8b5c-227cfe7d666b.png)

¯\\\_(ツ)\_/¯

**Comment by Blenux** [comment] 2018-04-16 06:45
ok I get that also now, I was using the debug way, still though doesn't give me a AES key though....

**Comment by Hiroshi97** [comment] 2018-05-26 12:23
Hi, I compiled aes-finder.exe by gcc while vs2017 couldn't. And I got this error.
I've tried to run CMD as admin, but still the same results.

![image](https://user-images.githubusercontent.com/39031279/40576026-116ec9ec-6133-11e8-8cd9-617dbd5aa025.png)

**Comment by mmozeiko** [comment] 2018-05-26 19:12
Try debugging result of OpenProcess function - what I mentioned in first comment.

**Comment by Hiroshi97** [comment] 2018-05-27 05:54
Hi,
Sorry I'm new to programming, so actually I don't know how to debug it correctly. But I've used a small test when I saw your open_process_begin() function. So your program only works with 32-bit applications while chrome.exe and my apps are 64-bit. I've checked on Firefox and it worked due to 32-bit.

Chrome 64-bit
![image](https://user-images.githubusercontent.com/39031279/40582872-4798c724-61c5-11e8-9765-299d3bf05383.png)
![image](https://user-images.githubusercontent.com/39031279/40582915-07627622-61c6-11e8-9db7-d686a9816c94.png)


Firefox and Steam (32-bit apps)
![image](https://user-images.githubusercontent.com/39031279/40582884-83924ec6-61c5-11e8-9597-d5da108edf42.png)
![image](https://user-images.githubusercontent.com/39031279/40582892-a177fd6e-61c5-11e8-8cdc-0c1d0466bc68.png)
![image](https://user-images.githubusercontent.com/39031279/40582902-c4b8aba2-61c5-11e8-9f0b-fb385aa15728.png)
![image](https://user-images.githubusercontent.com/39031279/40582916-117e2a66-61c6-11e8-9dd8-fc525bdc9751.png)

Too much images but I hope they are justifiable.

**Comment by Hiroshi97** [comment] 2018-05-27 06:09
Ok. I got the solution. I should compile the solution as Release x64.
Concerned to this note:
![image](https://user-images.githubusercontent.com/39031279/40583090-97d9933a-61ca-11e8-9270-275c83478f4c.png)

**Comment by mmozeiko** [comment] 2018-05-27 06:39
Excellent.
Closing issue, I assume this is same issue that @SatrioKamaludin had.

**Closed as completed by mmozeiko** 2018-05-27 06:39 UTC

**Comment by kovaci1** [comment] 2019-01-27 14:06
> That's the same process I've tried:
> 
> ![image](https://user-images.githubusercontent.com/1665010/38786955-0a645e64-40e0-11e8-8b5c-227cfe7d666b.png)
> 
> ¯\_(ツ)_/¯

i know this is close but just to know. if this show that mean can't get key (anti-debug anti-cheat i dont know) and need next lvl shit programin for get that ( sry for rudeness in the end)???(and no i dont want to use in fortin or any online game)
